# Generated by Django 4.2.7 on 2025-11-16 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_convert_veterinarian_to_sector_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin or sector veterinarian who approved this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('sector_vet', 'Sector Veterinarian'), ('local_vet', 'Local Veterinarian'), ('admin', 'Admin'), ('field_officer', 'Field Officer')], default='farmer', max_length=20),
        ),
    ]
