# Generated by Django 4.2.7 on 2025-11-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_password_reset_code_to_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarianprofile',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Veterinarian must explicitly set themselves to online via the app'),
        ),
    ]
