# Generated by Django 5.2.8 on 2025-11-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_make_email_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Phone number. For Rwanda: 078, 079, 073, or 072 followed by 7 digits (e.g., 0781234567). Sector vets can use international formats.', max_length=15, unique=True),
        ),
    ]
