# Generated by Django 4.2.7 on 2025-10-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_kinyarwanda', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('characteristics', models.TextField(blank=True)),
                ('average_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'db_table': 'breeds',
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tag_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('pregnant', 'Pregnant'), ('in_heat', 'In Heat'), ('deceased', 'Deceased'), ('sold', 'Sold')], default='healthy', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('last_deworming_date', models.DateField(blank=True, null=True)),
                ('last_health_check', models.DateField(blank=True, null=True)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('pregnancy_start_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('last_heat_date', models.DateField(blank=True, null=True)),
                ('next_expected_heat', models.DateField(blank=True, null=True)),
                ('daily_milk_production_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.breed')),
            ],
            options={
                'verbose_name': 'Livestock',
                'verbose_name_plural': 'Livestock',
                'db_table': 'livestock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivestockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_kinyarwanda', models.CharField(blank=True, max_length=100)),
                ('name_french', models.CharField(blank=True, max_length=100)),
                ('average_lifespan_years', models.PositiveIntegerField(default=10)),
                ('gestation_period_days', models.PositiveIntegerField(default=280)),
                ('vaccination_schedule', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Livestock Type',
                'verbose_name_plural': 'Livestock Types',
                'db_table': 'livestock_types',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('vaccine_type', models.CharField(blank=True, max_length=100)),
                ('vaccination_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='livestock.livestock')),
                ('veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'db_table': 'vaccination_records',
                'ordering': ['-vaccination_date'],
            },
        ),
        migrations.AddField(
            model_name='livestock',
            name='livestock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestocktype'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('check_type', models.CharField(choices=[('routine', 'Routine Check'), ('sick_visit', 'Sick Visit'), ('pregnancy_check', 'Pregnancy Check'), ('vaccination', 'Vaccination'), ('deworming', 'Deworming')], max_length=50)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('medications_prescribed', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medication_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.livestock')),
                ('veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'health_records',
                'ordering': ['-check_date'],
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='livestock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='livestock.livestocktype'),
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('morning_production', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('afternoon_production', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('evening_production', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_content', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('protein_content', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='livestock.livestock')),
            ],
            options={
                'verbose_name': 'Milk Production',
                'verbose_name_plural': 'Milk Production Records',
                'db_table': 'milk_production',
                'ordering': ['-production_date'],
                'unique_together': {('livestock', 'production_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('livestock_type', 'name')},
        ),
    ]
