# Generated by Django 5.2.8 on 2025-11-22 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_allow_null_tag_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='livestock',
            index=models.Index(fields=['status'], name='livestock_status_idx'),
        ),
        migrations.AddIndex(
            model_name='livestock',
            index=models.Index(fields=['owner'], name='livestock_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='livestock',
            index=models.Index(fields=['-created_at'], name='livestock_created_at_idx'),
        ),
    ]
