# Generated by Django 4.2.7 on 2025-11-16 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Sector veterinarian or admin who assigned this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casereport',
            name='assigned_veterinarian',
            field=models.ForeignKey(blank=True, help_text='Local veterinarian assigned to handle this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
