# Generated by Django 5.2.8 on 2025-11-22 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_casereport_assigned_at_casereport_assigned_by_and_more'),
        ('livestock', '0003_livestock_livestock_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='livestock',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific livestock affected. Leave blank for general cases.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_reports', to='livestock.livestock'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('investigation', 'Under Investigation'), ('diagnosed', 'Diagnosed'), ('treated', 'Treated'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='casereport',
            index=models.Index(fields=['status'], name='case_reports_status_idx'),
        ),
        migrations.AddIndex(
            model_name='casereport',
            index=models.Index(fields=['-reported_at'], name='case_reports_reported_idx'),
        ),
        migrations.AddIndex(
            model_name='casereport',
            index=models.Index(fields=['assigned_veterinarian'], name='case_reports_vet_idx'),
        ),
        migrations.AddIndex(
            model_name='casereport',
            index=models.Index(fields=['reporter'], name='case_reports_reporter_idx'),
        ),
        migrations.AddIndex(
            model_name='casereport',
            index=models.Index(fields=['status', 'reported_at'], name='case_reports_stat_rep_idx'),
        ),
    ]
