# Generated by Django 4.2.7 on 2025-12-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_casereport_livestock_alter_casereport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='farmer_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when farmer confirmed task completion', null=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='farmer_confirmed_completion',
            field=models.BooleanField(default=False, help_text='Farmer confirmation that the task/assignment has been completed'),
        ),
    ]
